# Generated by Django 4.0.3 on 2023-03-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuron_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=30)),
                ('url', models.FileField(null=True, upload_to='audio/')),
                ('primary', models.CharField(max_length=60)),
                ('range', models.JSONField(default=dict)),
            ],
        ),
        migrations.DeleteModel(
            name='SolutionAsUrl',
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-at']},
        ),
        migrations.RenameField(
            model_name='game',
            old_name='secondary_url',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='primary',
            new_name='badge',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='image_url',
            new_name='cover',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='story',
            name='image_url',
        ),
        migrations.AddField(
            model_name='doctor',
            name='location',
            field=models.CharField(default='Ahmedabad', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
