# Generated by Django 4.0.3 on 2023-03-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuron_main', '0002_therapy_delete_solutionasurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/image/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(null=True, upload_to='media/image/'),
        ),
        migrations.AlterField(
            model_name='therapy',
            name='url',
            field=models.FileField(null=True, upload_to='media/audio/'),
        ),
    ]
