# Generated by Django 4.0.3 on 2023-03-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuron_main', '0004_alter_game_avatar_alter_game_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='redirect_url',
            field=models.URLField(default='https://supermarioplay.com/'),
        ),
    ]
