# Generated by Django 4.0.3 on 2023-03-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuron_main', '0007_remove_doctor_redirect_url_game_redirect_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='range',
        ),
        migrations.AlterField(
            model_name='game',
            name='redirect_url',
            field=models.URLField(),
        ),
    ]
