# Generated by Django 4.0.3 on 2023-03-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuron_main', '0008_remove_doctor_range_alter_game_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='John Doe', max_length=30),
        ),
    ]
