# Generated by Django 4.0.3 on 2023-04-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuron_main', '0009_doctor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='story',
            name='topic',
            field=models.CharField(max_length=50),
        ),
    ]
